#! /bin/sh
xrandr -r 75
sxhkd &
bash  ~/.config/polybar/onedark-theme/launch.sh &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI 

bspc config border_width         0
bspc config window_gap           8

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true


xsetroot -cursor_name left_ptr

variety
